project:
  type: website

website:
  title: "IS415-HealthGeo-Cambodia"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Project Overview"
        href: "Project/Proposal.html"
      - text: "Project Poster"
        href: "Project/Poster.html"
      - text: "Prototype of Features"
        menu:
          - text: "Exploratory Data Analysis"
            href: ""
          - text: "Network Constrained Spatial Point Pattern Analysis"
            href: "Prototype/Take-home_Ex03/Take-home_Ex03.html"
          - text: "Spatial Autocorrelation"
            href: "Prototype/Spatial_Autocorrelation/SpatialAutocorrelation.html"
    right:
      - icon: github
        href: https://github.com
        aria-label: GitHub

format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: visual

