project:
  type: website

website:
  title: "IS415-HealthGeo-India"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Project Proposal"
        menu:
          - text: "Project Proposal"
            href: "Project/Proposal.html"

format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: visual

